- name: variables to print
  hosts: web
  vars:
    NAME: "Yash"
    age: "24"
    location: "hyd"

  tasks:
   - name: print the data
     ansible.builtin.debug: 
       msg: "Hi , I am {{NAME}} and {{age}} yr young and at {{location}} now"

  - name: print the data again
    vars:
    ansible.builtin.debug: 
     NAME: "bobby"
       msg: "Hi , I am {{NAME}} and {{age}} yr young and at {{location}} now"