- name: variables to print
  hosts: web
  vars: #play level variables , all tasks in this play has access to these vars
    NAME: "Yash"
    age: "24"
    location: "hyd"

  tasks:
   - name: print the data
     ansible.builtin.debug: 
      msg: "Hi , I am {{NAME}} and {{age}} yr young and at {{location}} now"

   - name: print the data again
     vars:
      NAME: "bobby" #task level vars will override play level vars
     ansible.builtin.debug: 
      msg: "Hi , I am {{NAME}} and {{age}} yr young and at {{location}} now"

   - name: print the data
     vars:
     age: "23"
     ansible.builtin.debug: 
      msg: "Hi , I am {{NAME}} and {{age}} yr young and at {{location}} now"