- name: variables from files
  hosts: web
  vars_files:
    - vars.yaml
  tasks:
    - name: print the info
      ansible.builtin.debug:
        msg: "Hi , I am {{Name}} and {{age}} yr young and at {{location}} now"