- name: variables from files
  hosts: web #ansible will check in this inventory file and if vars or anything is present will read and uses
  tasks:
    - name: print the info
      ansible.builtin.debug:
        msg: "Hi , I am {{Name}} and {{Age}} yr young and at {{Location}} now"