- name: inputs to print
  hosts: web
  tasks:
    - name: print my info
      ansible.builtin.debug:
        msg: "Hello {{NAME}} and and your incident details are {{INCIDENT}}"
#use -e or --extra-vars in commandline to give input as arguments