- name: variables from files
  hosts: web 
  vars:
    Name: "Chinnu from PLAY level"
    Age: "25"
    Location: "Satya's heart"
  vars_files:
    - vars.yaml
  vars_prompt:
    - name: Name
      prompt: Please enter your name
      private: false #prompts are by default confidential , so you cannot see what u enter , but with false you can
    - name: Age
      prompt: Please enter your age , shh!!! we will keep it a secret
      private: false
    - name: Location
      prompt: Please enter your location
      private: false
  tasks:
    - name: variables from files
      ansible.builtin.debug:
        msg: "Hi , I am {{Name}} and {{Age}} yr young and at {{Location}} now"