- name : to check if number is greater or equals to 10
  hosts: localhost
  connection: local
  vars_prompt:
  - name: number
    prompt: please enter the number
    private: false
    tasks:
      - name: print this if less than 10
        ansible.builtin.debug:
          msg: " Given number {{number}} is less than 10"
        when: number | int < 10
      
      - name: print this if greater than or equals 10
        ansible.builtin.debug:
          msg: "Given number {{number}} is greater or equals 10 "
        when: number | int >= 10