- name: loops demo
  hosts: web
  become: yes
  tasks:
    - name: print names
      ansible.builtin.package:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      loop:
      - { name: 'mysql', state: absent }
      - { name: 'nginx', state: absent }
      - { name: 'postfi', state: absent }