- name: loops demo
  hosts: local
  connection: local
  vars_prompt:
    name: "Name"
    prompt: "what is your name?"
    private: false # just used loop unnecesarily , wanted to do the prompt practice

  tasks:
    - name: print names
      ansible.builtin.debug:
        msg: " HELLO {{ Name }}"
      loop:
       - chinnu
       - bob