- name: filters/functions demo
  hosts: local
  connection: local
  tasks:
    - name: print default variable
      ansible.builtin.debug:
        msg: " Hello {{ user | default('Ansible') }}"

    - name: convert to UPPER_CASE
      vars:
        greeting: "HEllO RamESh"
      ansible.builtin.debug:
        msg: "{{ greeting | upper }}"

    - name: convert to UPPER_CASE
      vars:
        greeting: "HEllO RamESh"
      ansible.builtin.debug:
        msg: "{{ greeting | lower }}"

    - name: print unique
      vars:
        numbers: [1,2,2,5,77,3,3,7,8,9,0,43,43,34]
      ansible.builtin.debug:
        msg: "{{ numbers | unique }}"

    - name: print min & max
      vars:
        numbers: [1,2,2,5,77,3,3,7,8,9,0,43,43,34]
      ansible.builtin.debug:
        msg: "Min: {{ numbers | min }}, Max: {{ numbers | max }}"

    - name: convert maps to list
      vars:
        data:
          name: "chinnu"
          age: 24
          location: "satya's heart"
      ansible.builtin.debug:
        msg: "{{ data | dict2items }}"
       