- name: filters/functions demo
  hosts: local
  connection: local
  tasks:
    - name: print default variable
      ansible.builtin.debug:
        msg: " Hello {{ user | default('Ansible') }}"

    - name: convert to UPPER_CASE
      vars:
        greeting: "HEllO RamESh"
      ansible.builtin.debug:
        msg: "{{ greeting | upper }}"

    - name: convert to UPPER_CASE
      vars:
        greeting: "HEllO RamESh"
      ansible.builtin.debug:
        msg: "{{ greeting | lower }}"
       